<a href="https://colab.research.google.com/github/gloriaypradal/Bakery_Sales_Predictions/blob/main/Merging_lookup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [21]:
df_holds = pd.read_csv("lansa.csv")
df_engine = pd.read_csv("engine list.csv")

df_holds.head()

,Item,Crate,Year,VIN/HIN,ENGINE #,Assembly Date,A-Time,Crate Date,C-Time,K60,Held By,Held Date,Line,K60 Date,Ship Date,Location
0,RFT00A-D251-GN1,R80057,2022,JKARFCA16NB515394,RFT00AE021114,20220103,70127,20220103,131946,1,NaN,0,ATV1,20220104,20220118,D 8 2
1,RFT00A-D251-GN1,R80065,2022,JKARFCA18NB515395,RFT00AE021113,20220103,72547,20220103,133703,1,NaN,0,ATV1,20220104,20220110,D 8 2
2,RFT00B-B251-GY1,R80072,2022,JKARFCB1XNB502727,RFT00AE021108,20220103,74356,20220103,135349,1,NaN,0,ATV1,20220104,20220105,C 5 3
3,RFT00A-D251-GN1,R80076,2022,JKARFCA1XNB515396,RFT00AE021110,20220103,75538,20220103,140217,1,NaN,0,ATV1,20220104,20220107,D 8 2
4,RFT00A-D251-GN1,R80083,2022,JKARFCA11NB515397,RFT00AE021047,20220103,80852,20220103,142815,1,NaN,0,ATV1,20220104,20220106,D 8 2

In [22]:
df_engine.rename(columns = {'Suspected engine list':'ENGINE #'}, inplace = True)

In [23]:
df_engine.head()

        ENGINE #         Status
0  RFT00AE022982  Factory stock
1  RFT00AE022983  Factory stock
2  RFT00AE022991  Factory stock
3  RFT00AE023071    Dist. Stock
4  RFT00AE023150  KMM inventory

In [24]:
df_total = pd.merge(df_engine, df_holds, how = "inner", on = "ENGINE #")

In [25]:
df_total

,ENGINE #,Status,Item,Crate,Year,VIN/HIN,Assembly Date,A-Time,Crate Date,C-Time,K60,Held By,Held Date,Line,K60 Date,Ship Date,Location
0,RFT00AE022982,Factory stock,RFT00A-D993-GN1,R96991,2022,JKARFCA13NB517264,20220413,120800,20220414,94638,S,JHAMILTON,20220609,ATV1,20220414,0,C 8 1
1,RFT00AE022983,Factory stock,RFT00A-D993-RD1,R96987,2022,JKARFCA11NB517263,20220413,115713,20220414,91857,S,JHAMILTON,20220609,ATV1,20220414,0,C 6 1
2,RFT00AE022991,Factory stock,RFT00A-D993-GN1,R96979,2022,JKARFCA16NB517260,20220413,112509,20220414,84348,S,JHAMILTON,20220609,ATV1,20220414,0,C 8 1
3,RFT00AE023071,Dist. Stock,RFT00B-B251-GY1,S02399,2022,JKARFCB15NB503445,20220513,105636,20220516,75708,1,NaN,0,ATV1,20220516,20220518,D 7 1
4,RFT00AE023248,Dist. Stock,RFT00A-D251-RD1,S00251,2022,JKARFCA16NB517484,20220502,113631,20220503,102638,1,NaN,0,ATV1,20220509,20220513,D 7 3
5,RFT00AE023265,Dist. Stock,RFT00B-B255-GY1,S00308,2022,JKARFCB18NB503410,20220502,134431,20220503,121256,1,NaN,0,ATV1,20220503,20220505,E C 4
6,RFT00AE023267,Dist. Stock,RFT00A-D251-GN1,S00214,2022,JKARFCA10NB517481,20220502,102732,20220503,90505,1,NaN,0,ATV1,20220509,20220513,D 7 2
7,RFT00AE023269,Dist. Stock,RFT00A-D251-GN1,S00197,2022,JKARFCA19NB517480,20220502,95449,20220503,83920,1,NaN,0,ATV1,20220509,20220513,D 7 2
8,RFT00AE023433,Retail,RFT00B-B251-GY1,R95747,2022,JKARFCB12NB503189,20220407,95517,20220407,155343,1,NaN,0,ATV1,20220407,20220408,D 8 3
9,RFT00AE023926,KMM inventory,RFT00A-E251-RD1,S07079,2023,JKARFCA1XPB518043,20220608,150002,20220609,104325,Q,JHAMILTON,20220609,ATV1,0,0,B 9 4
10,RFT00AE024185,Dist. Stock,RFT00A-D251-RD1,S03019,2022,JKARFCA10NB517626,20220517,103546,20220519,102516,1,NaN,0,ATV1,20220519,20220603,D 7 1
11,RFT00AE024220,Dist. Stock,RFT00A-D251-RD1,S02868,2022,JKARFCA14NB517614,20220516,144839,20220517,111226,1,NaN,0,ATV1,20220517,20220519,D 8 2
12,RFT00AE024256,Dist. Stock,RFT00A-D251-GN1,R99378,2022,JKARFCA15NB517430,20220427,132932,20220428,132322,1,NaN,0,ATV1,20220509,20220513,D 7 2
13,RFT00AE024260,Dealer stock,RFT00B-B252-GY1,R97706,2022,JKARFCB16NB503339,20220419,110337,20220420,82455,1,NaN,0,ATV1,20220420,20220427,D 9 2
14,RFT00AE024271,Retail,RFT00C-B251-GN1,R97726,2022,JKARFCC14NB501698,20220419,115123,20220420,90716,1,NaN,0,ATV1,20220420,20220421,D 8 2
15,RFT00AE024272,Retail,RFT00C-B251-GN1,R97742,2022,JKARFCC16NB501699,20220419,122927,20220420,95828,1,NaN,0,ATV1,20220420,20220421,D 8 2
16,RFT00AE025101,KMM inventory,RFT00A-E251-RD1,S08684,2023,JKARFCA19PB518146,20220617,133658,0,0,Q,JHAMILTON,20220618,ATV1,0,0,NaN
17,RFT00AE025102,KMM inventory,RFT00A-E251-RD1,S08676,2023,JKARFCA17PB518145,20220617,131826,0,0,Q,JHAMILTON,20220618,ATV1,0,0,NaN

In [26]:
df_total.to_csv("engines_conc.csv")